logo: WD # add logo name
title: Waterfalls of Data - Data science in the world of software dev
description: > # this means to ignore newlines until "baseurl:"
  Data science in the world of software dev
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
#video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-title:  Waterfalls of Data # add banner title
banner-desc: Data science in the world of software dev # add banner description

# Author settings
author-pic:  climb_sketch_mharris.JPG # your photo
author-name: Micheleen Harris # your name
about-author: pythonista data science dev glacier seeker sock knitter # about author
email:  # your email
phone:  # your pnone number
website: https://michhar.github.io # you website

# Social link
github_url: https://github.com/michhar   # add url link
twitter_url: https://twitter.com/rheartpython  # add url link
instagram_url: # add url link
pinterest_url: # add url link
dribbble_url:  # add url link
facebook_url:  # add url link

# Disqus
discus_identifier:  # add your discus identifier

# Newsletter
#mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics:

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]